# Generated by Django 3.2 on 2021-05-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='is_lock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
