# Generated by Django 3.2 on 2021-05-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_myfile_is_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myfile',
            name='index',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myfile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
