# Generated by Django 3.2 on 2021-05-18 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0003_auto_20210517_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('doc', models.FileField(upload_to='archived_doc/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('expiary_date', models.DateTimeField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('archive_date', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
